-- Run with Supabase CLI or apply in the Supabase SQL editor before enabling production writes.
create extension if not exists pgcrypto;

create table if not exists public.tourists (
    id uuid primary key default gen_random_uuid(),
    tourist_id text not null unique,
    name text not null,
    phone text unique,
    email text unique,
    role text not null default 'tourist',
    emergency_contact text,
    pace text not null default 'balanced',
    interests jsonb not null default '[]'::jsonb,
    verified boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.sos_alerts (
    id text primary key,
    user_name text not null,
    emergency_contact text,
    latitude double precision not null check (latitude between -90 and 90),
    longitude double precision not null check (longitude between -180 and 180),
    battery_level smallint check (battery_level between 0 and 100),
    status text not null default 'ACTIVE',
    nearest_police jsonb,
    nearest_hospital jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.itineraries (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    hours integer not null check (hours between 1 and 72),
    preference text not null,
    pace text not null default 'balanced',
    stops jsonb not null default '[]'::jsonb,
    safety_briefing text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.groups (
    id text primary key,
    name text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.group_members (
    group_id text not null references public.groups(id) on delete cascade,
    user_name text not null,
    latitude double precision not null check (latitude between -90 and 90),
    longitude double precision not null check (longitude between -180 and 180),
    is_anchor boolean not null default false,
    updated_at timestamptz not null default now(),
    primary key (group_id, user_name)
);

create table if not exists public.auth_otps (
    contact text primary key,
    code_hash text not null,
    expires_at double precision not null,
    requested_at double precision not null,
    attempts integer not null default 0 check (attempts between 0 and 5)
);

create index if not exists sos_alerts_created_at_idx on public.sos_alerts (created_at desc);
create index if not exists itineraries_user_created_idx on public.itineraries (user_id, created_at desc);
create index if not exists group_members_group_idx on public.group_members (group_id);

alter table public.tourists enable row level security;
alter table public.sos_alerts enable row level security;
alter table public.itineraries enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.auth_otps enable row level security;

-- Deliberately no anon/authenticated policies: all writes must go through the backend
-- using SUPABASE_SERVICE_ROLE_KEY. Never ship that key to the browser.
